services:
  # Service PostgreSQL Database
  - type: pserv
    name: pharmacie-db
    plan: free
    env: postgresql
    version: "15"
    envVars:
      - key: POSTGRES_DB
        value: pharmacie_db
      - key: POSTGRES_USER
        value: pharmacie_user
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Service Backend Spring Boot
  - type: web
    name: pharmacie-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/pharmacie-spring-jpa-1.0-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: deploy
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pharmacie-db
          property: connectionString
        value: jdbc:postgresql://{{ POSTGRES_HOST }}:{{ POSTGRES_PORT }}/pharmacie_db
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pharmacie-db
          property: user
        value: pharmacie_user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pharmacie-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: POSTMARK_API_KEY
        value: 3c6a5f2a-8642-47ac-b90c-34d3e58470ee
